acc <- read.table("acc.txt", sep = "\t")
ori <- read.table("orient.txt", sep = "\t")
colnames(acc) <- c("deviceID", "sensorName", "x", "y", "z")
par(mfrow=c(3,1))
plot(acc$x, type = "l")
lines(filter(acc$x, rep(1/20, 20), sides = 1), col = "blue")
lines(filter(acc$x, rep(1/20, 20), sides = 2), col = "red")
plot(acc$y, type = "l")
lines(filter(acc$y, rep(1/20, 20), sides = 1), col = "blue")
lines(filter(acc$y, rep(1/20, 20), sides = 2), col = "red")
plot(acc$z, type = "l")
lines(filter(acc$z, rep(1/20, 20), sides = 1), col = "blue")
lines(filter(acc$z, rep(1/20, 20), sides = 2), col = "red")